/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzzi;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author Cristian M
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        this.setTitle("Sistema Fuzzi");
        this.setResizable(false);
        this.setLocation(300,100 );
        this.setSize(800, 500);
        this.setIconImage(new ImageIcon(getClass().getResource("imagen/logos.jpg")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        errorD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        errorp = new javax.swing.JTextField();
        centroide = new javax.swing.JLabel();
        errora = new javax.swing.JTextField();
        matriz = new javax.swing.JTextField();
        matriz1 = new javax.swing.JTextField();
        matriz2 = new javax.swing.JTextField();
        matriz3 = new javax.swing.JTextField();
        matriz4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        centro = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema Fuzzy");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(280, 10, 240, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 0));
        jLabel3.setText(" Error Diferencial : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 280, 120, 40);

        errorD.setEditable(false);
        errorD.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        errorD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        errorD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorDActionPerformed(evt);
            }
        });
        getContentPane().add(errorD);
        errorD.setBounds(370, 280, 120, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sumatoria");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 50, 210, 40);

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        getContentPane().add(calcular);
        calcular.setBounds(40, 270, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 0));
        jLabel5.setText("Ingrese Error Pasado: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 170, 150, 40);

        errorp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        errorp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 0)));
        errorp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorpActionPerformed(evt);
            }
        });
        getContentPane().add(errorp);
        errorp.setBounds(30, 220, 120, 30);

        centroide.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        centroide.setForeground(new java.awt.Color(204, 204, 0));
        centroide.setText("Centroide:");
        getContentPane().add(centroide);
        centroide.setBounds(560, 320, 90, 40);

        errora.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        errora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        errora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                erroraActionPerformed(evt);
            }
        });
        getContentPane().add(errora);
        errora.setBounds(30, 140, 120, 30);

        matriz.setEditable(false);
        matriz.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(matriz);
        matriz.setBounds(610, 250, 140, 30);

        matriz1.setEditable(false);
        matriz1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(matriz1);
        matriz1.setBounds(610, 90, 140, 30);

        matriz2.setEditable(false);
        matriz2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(matriz2);
        matriz2.setBounds(610, 130, 140, 30);

        matriz3.setEditable(false);
        matriz3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(matriz3);
        matriz3.setBounds(610, 170, 140, 30);

        matriz4.setEditable(false);
        matriz4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(matriz4);
        matriz4.setBounds(610, 210, 140, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("Ingrese Error Actual: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 90, 150, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 0));
        jLabel8.setText("SNG:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(570, 80, 40, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 0));
        jLabel9.setText("SNP:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(570, 120, 40, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 0));
        jLabel10.setText("SZ:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(570, 160, 40, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 0));
        jLabel11.setText("SPP:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(570, 200, 40, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 0));
        jLabel12.setText("EPG");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(470, 70, 40, 20);

        centro.setEditable(false);
        centro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 0)));
        getContentPane().add(centro);
        centro.setBounds(630, 320, 150, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(460, 210, 60, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(220, 90, 60, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(280, 90, 60, 30);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(340, 90, 60, 30);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(400, 90, 60, 30);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(460, 90, 60, 30);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(220, 120, 60, 30);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(280, 120, 60, 30);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(340, 120, 60, 30);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(400, 120, 60, 30);
        getContentPane().add(jTextField11);
        jTextField11.setBounds(460, 120, 60, 30);
        getContentPane().add(jTextField12);
        jTextField12.setBounds(220, 150, 60, 30);
        getContentPane().add(jTextField13);
        jTextField13.setBounds(280, 150, 60, 30);
        getContentPane().add(jTextField14);
        jTextField14.setBounds(340, 150, 60, 30);
        getContentPane().add(jTextField15);
        jTextField15.setBounds(400, 150, 60, 30);
        getContentPane().add(jTextField16);
        jTextField16.setBounds(460, 150, 60, 30);
        getContentPane().add(jTextField17);
        jTextField17.setBounds(220, 180, 60, 30);
        getContentPane().add(jTextField18);
        jTextField18.setBounds(280, 180, 60, 30);
        getContentPane().add(jTextField19);
        jTextField19.setBounds(340, 180, 60, 30);
        getContentPane().add(jTextField20);
        jTextField20.setBounds(400, 180, 60, 30);
        getContentPane().add(jTextField21);
        jTextField21.setBounds(460, 180, 60, 30);
        getContentPane().add(jTextField22);
        jTextField22.setBounds(220, 210, 60, 30);
        getContentPane().add(jTextField23);
        jTextField23.setBounds(280, 210, 60, 30);
        getContentPane().add(jTextField24);
        jTextField24.setBounds(340, 210, 60, 30);
        getContentPane().add(jTextField25);
        jTextField25.setBounds(400, 210, 60, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 0));
        jLabel13.setText("SPG:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(570, 240, 40, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 0));
        jLabel14.setText("DEPG");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(180, 100, 40, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 0));
        jLabel15.setText("ENP");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(290, 70, 40, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 0));
        jLabel16.setText("EZ");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(350, 70, 40, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 0));
        jLabel17.setText("EPP");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(410, 70, 40, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 0));
        jLabel18.setText("ENG");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(230, 70, 40, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 0));
        jLabel19.setText("DENG");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(180, 220, 40, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 0));
        jLabel20.setText("DENP");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(180, 190, 40, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 0));
        jLabel21.setText("DEZ");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(190, 160, 30, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 0));
        jLabel22.setText("DEPP");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(180, 130, 40, 20);

        limpiar.setText("Limpiar");
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar);
        limpiar.setBounds(700, 433, 80, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzi/imagen/fu2.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 340, 290, 115);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fuzzi/imagen/fondo.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 820, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    

//Error negativo grande
	public double eng( double entrada){
		if(entrada<-10){
			return 1;
		}
		else{
			if(entrada>=-10 && entrada<-5){
				return (-.2*entrada)-1;
			}
			else{
				return 0;
			}
		}
	}
	//Error negativo pequeño
	public double enp(double entrada){
		
		if(entrada<-10){
			return 0;
		}
		else{
			if(entrada>=-10 && entrada<-5){
				return (.2*entrada)+2;
			}
			else{
				if(entrada>=-5 && entrada<0){
					return (-.2*entrada);
				}
				else{
					return 0;
				}
			}
		}
	}
	//error medio 0
	public  double ez(double entrada){
		if(entrada<-5){
			return 0;
		}
		else{
			if(entrada>=-5 && entrada<0){
				return (.2*entrada)+1;
			}
			else{
				if(entrada>=0 && entrada<5){
					return (-.2*entrada)+1;
				}
				else{
					return 0;
				}
			}
		}
	}
	//error positivo pequeño
	public  double epp(double entrada){
			if(entrada<0){
				return 0;
			}
			else{
				if(entrada>=0 && entrada<5){
					return (.2*entrada);
				}
				else{
					if(entrada>=5 && entrada<10){
						return (-.2*entrada)+2;
					}
					else{
						return 0;
					}
				}
			}
	}
	//error positivo grande
	public  double epg(double entrada){	
		if( entrada<5){
			return 0;
		}
		else{
			if(entrada>=5 && entrada<10){
				return (.2*entrada)-1;
			}
			else{
				return 1;
			}
		}
	}

	
	////////////////////////////////////////
	
	// error diferencial 
	
	//Error negativo grande
	public double deng( double entrada){
		if(entrada<-4){
			return 1;
		}
		else{
			if(entrada>=-4 && entrada<-2){
				return (-.5*entrada)-1;
			}
			else{
				return 0;
			}
		}
	}
	//Error negativo pequeño
	public double denp(double entrada){
		
		if(entrada<-4){
			return 0;
		}
		else{
			if(entrada>=-4 && entrada<-2){
				return (.5*entrada)+2;
			}
			else{
				if(entrada>=-2 && entrada<0){
					return (-.5*entrada);
				}
				else{
					return 0;
				}
			}
		}
	}
	//error medio 0
	public  double dez(double entrada){
		if(entrada<-2){
			return 0;
		}
		else{
			if(entrada>=-2 && entrada<0){
				return (.5*entrada)+1;
			}
			else{
				if(entrada>=0 && entrada<2){
					return (-.5*entrada)+1;
				}
				else{
					return 0;
				}
			}
		}
	}
	//error positivo pequeño
	public  double depp(double entrada){
			if(entrada<0){
				return 0;
			}
			else{
				if(entrada>=0 && entrada<2){
					return (.5*entrada);
				}
				else{
					if(entrada>=2 && entrada<4){
						return (-.5*entrada)+2;
					}
					else{
						return 0;
					}
				}
			}
	}
	//error positivo grande
	public  double depg(double entrada){	
		if( entrada<2){
			return 0;
		}
		else{
			if(entrada>=2 && entrada<4){
				return (.5*entrada)-1;
			}
			else{
				return 1;
			}
		}
	}
	
	//diferencial de error
	public  String diferencial(double derror, double error){
		
		return "fin";	
	}
	
	//sumas
	public double spg (double derror , double error){
		return  epg(error)*dez(derror) + epg(error)*depp(derror) + enp(error)*depg(derror) + eng(error)*depg(derror) + eng(error)*depp(derror);
	}
	public double spp(double derror , double error){
		return epg(error)*depg(derror) + epp(error)*depg(derror) + epp(error)*depp(derror) + epp(error)*dez(derror) + ez(error)*depg(derror) + ez(error)*depp(derror) + enp(error)*depp(derror);
	}
	public double sz(double derror , double error){
		return ez(error)*dez(derror);
	}
	public double snp(double derror , double error){
	
		return epp(error)*denp(derror) + epp(error)*deng(derror) +ez(error)*denp(derror)+ ez(error)*deng(derror)+enp(error)*dez(derror)+enp(error)*denp(derror)+enp(error)*deng(derror);
	}
	public double sng(double derror , double error){
		return epg(error)*denp(derror) + epg(error)*deng(derror)+ eng(error)*dez(derror)+eng(error)*denp(derror)+eng(error)*deng(derror);
	}
	
	//centroide
	public double centroide (double x, double y){
		double mspg = spg(x, y)* 10;
		double mspp = spp(x, y)* 5;
		double msz = sz(x, y)*0;
		double msnp = snp(x, y) * -5;
		double msng = sng(x, y) * -10;
		double suma=spg(x, y) + spp(x, y) + sz(x, y) + snp(x, y) +sng(x, y);
		double sumam = (mspg +mspp+msz+msnp+msng) / suma;
		 return sumam;
		
	}
    
    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        // TODO add your handling code here:
        double errorpasado = 0;
        double erroratual = 0;
        Clase ok = new Clase();
        erroratual =  Double.parseDouble(this.errora.getText());
        errorpasado = Double.parseDouble(this.errorp.getText());
        
        double errorDi = erroratual-errorpasado;
        errorD.setText(String.valueOf(errorDi));
        
        matriz1.setText(String.valueOf(ok.sng(errorDi, erroratual)));
        matriz2.setText(String.valueOf(ok.snp(errorDi, erroratual)));
        matriz3.setText(String.valueOf(ok.sz(errorDi, erroratual)));
        matriz4.setText(String.valueOf(ok.spp(errorDi, erroratual)));
        matriz.setText(String.valueOf(ok.spg(errorDi, erroratual)));
       
        
        centro.setText(String.valueOf(ok.centroide(errorDi, erroratual)));
       // matriz.setText(String.valueOf( diferencial(errorDi, erroratual)));
        //area.setText(String.valueOf(ok.diferencial(errorDi, erroratual)));
        /*
        jTextField2.setText(String.valueOf(ok.okey.diferencial(errorDi, erroratual)));
         jTextField3.setText(String.valueOf(diferencial(errorDi, erroratual)));
          jTextField4.setText(String.valueOf(diferencial(errorDi, erroratual)));
           jTextField5.setText(String.valueOf(diferencial(errorDi, erroratual)));
            jTextField6.setText(String.valueOf(diferencial(errorDi, erroratual)));
        */
        
            if(eng(erroratual)!=0){
				if(deng(errorDi)!=0){
                                     jTextField22.setText(String.valueOf("SNG: "+eng(erroratual)*deng(errorDi) ));
					//System.out.println("SNG " + eng(error)*deng(derror));
				} 
				if(denp(errorDi)!=0){
                                        jTextField17.setText(String.valueOf("SNG: "+ eng(erroratual)*denp(errorDi) ));
				//	System.out.println("SNG "+ eng(error)*denp(derror));
				}
				if((dez(errorDi))!=0){
                                     jTextField12.setText(String.valueOf("SNG: "+ eng(erroratual)*dez(errorDi) ));
				//	System.out.println("SNG " + eng(error)*dez(derror));
				}
				if((depp(errorDi))!=0){
                                    jTextField1.setText(String.valueOf("SPG: "+eng(erroratual)*depp(errorDi) ));
                                    
				//	System.out.println("SPG " + eng(error)*depp(derror));
				}
				if((depg(errorDi))!=0){
                                    jTextField2.setText(String.valueOf("SPG: "+eng(erroratual)*depg(errorDi) ));
                                    return;
				//	System.out.println("SPG " + eng(error)*depg(derror));
				}
			}
			if(enp(erroratual)!=0){
				if(deng(errorDi)!=0){
                                   jTextField23.setText(String.valueOf("SNP: "+ enp(erroratual)*deng(errorDi) ));
				//	System.out.println("SNP " + enp(error)*deng(derror));
				}
				if(denp(errorDi)!=0){
                                    jTextField18.setText(String.valueOf("SNP: "+ enp(erroratual)*denp(errorDi) ));
				//	System.out.println("SNP " + enp(error)*denp(derror));
				}
				if((dez(errorDi))!=0){
                                    jTextField13.setText(String.valueOf("SNP: "+ enp(erroratual)*dez(errorDi) ));
				//	System.out.println("SNP " + enp(error)*dez(derror));
				}
				if((depp(errorDi))!=0){
                                    jTextField8.setText(String.valueOf("SPP: "+ enp(erroratual)*depp(errorDi) ));
				//	System.out.println("SPP " + enp(error)*depp(derror));
				}
				if((depg(errorDi))!=0){
                                    jTextField3.setText(String.valueOf("SPG: "+ enp(erroratual)*depp(errorDi) ));
				//	System.out.println("SPG " + enp(error)*depg(derror));
				}
				 
			}
			if(ez(erroratual)!=0){
				if(deng(errorDi)!=0){
                                    jTextField24.setText(String.valueOf("SNP: "+ ez(erroratual)*deng(errorDi) ));
					//System.out.println("SNP "+ ez(error)*deng(derror));
				}
				if(denp(errorDi)!=0){
                                   jTextField19.setText(String.valueOf("SNP: "+ ez(erroratual)*denp(errorDi) ));
					//System.out.println("SNP "+ ez(error)*denp(derror));
				}
				if((dez(errorDi))!=0){
                                    jTextField14.setText(String.valueOf("SZ: "+ ez(erroratual)*dez(errorDi) ));
				//	System.out.println("SZ " +ez(error)*dez(derror));
				}
				if((depp(errorDi))!=0){
                                    jTextField9.setText(String.valueOf("SPP: "+ ez(erroratual)*depp(errorDi) ));
				//	System.out.println("SPP "+ez(error)*depp(derror));
				}
				if((depg(erroratual))!=0){
                                    jTextField4.setText(String.valueOf("SPP: "+ez(erroratual)*depg(errorDi) ));
				//	System.out.println("SPP "+ez(error)*depg(derror));
				}
			}
			if(epp(erroratual)!=0){
				if(deng(errorDi)!=0){
                                    jTextField25.setText(String.valueOf("SNP: "+ epp(erroratual)*deng(errorDi) ));
					//System.out.println("SNP "+epp(error)*deng(derror));
				}
				if(denp(errorDi)!=0){
                                   jTextField20.setText(String.valueOf("SNP: "+ epp(erroratual)*denp(errorDi) ));
				//	System.out.println("SNP "+epp(error)*denp(derror));
				}
				if((dez(errorDi))!=0){
                                   jTextField15.setText(String.valueOf("SPP: "+ epp(erroratual)*dez(errorDi) ));
				//	System.out.println("SPP "+epp(error)*dez(derror));
				}
				if((depp(errorDi))!=0){
                                    jTextField10.setText(String.valueOf("SPP: "+ epp(erroratual)*depp(errorDi) ));
				//	System.out.println("SPP "+epp(error)*depp(derror));
				}
				if((depg(errorDi))!=0){
                                    jTextField5.setText(String.valueOf("SPP: "+epp(erroratual)*depg(errorDi) ));
				//	System.out.println("SPP "+epp(error)*depg(derror));
				}
			}
			if(epg(erroratual)!=0){
				if(deng(errorDi)!=0){
                               jTextField1.setText(String.valueOf("SNG: "+ epg(erroratual)*deng(errorDi) ));
					//System.out.println("SNG " +epg(error)*deng(derror));
				}
				if(denp(errorDi)!=0){
                                  jTextField21.setText(String.valueOf("SNG: "+ epg(erroratual)*denp(errorDi) ));
				//	System.out.println("SNG "+epg(error)*denp(derror));
				}
				if((dez(errorDi))!=0){
                                    jTextField16.setText(String.valueOf("SPG: "+ epg(erroratual)*dez(errorDi) ));
				//	System.out.println("SPG "+epg(error)*dez(derror));
				}
				if((depp(errorDi))!=0){
                                    jTextField11.setText(String.valueOf("SPG: "+ epg(erroratual)*depp(errorDi) ));
				//	System.out.println("SPG "+epg(error)*depp(derror));
				}
				if((depg(errorDi))!=0){
                                    jTextField6.setText(String.valueOf("SPP: "+ epg(erroratual)*depg(errorDi) ));
				//	System.out.println("SPP "+epg(error)*depg(derror));
				}
			}
    }//GEN-LAST:event_calcularActionPerformed

    private void errorDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorDActionPerformed

    private void errorpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_errorpActionPerformed

    private void erroraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_erroraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_erroraActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        // TODO add your handling code here:
        errora.setText(String.valueOf(""));
        errorp.setText(String.valueOf(""));
        errorD.setText(String.valueOf(""));
        centro.setText(String.valueOf(""));
        matriz.setText(String.valueOf(""));
        matriz1.setText(String.valueOf(""));
        matriz2.setText(String.valueOf(""));
        matriz3.setText(String.valueOf(""));
        matriz4.setText(String.valueOf(""));
        jTextField1.setText(String.valueOf(""));
        jTextField2.setText(String.valueOf(""));
        jTextField3.setText(String.valueOf(""));
        jTextField4.setText(String.valueOf(""));
        jTextField5.setText(String.valueOf(""));
        jTextField6.setText(String.valueOf(""));
        jTextField7.setText(String.valueOf(""));
        jTextField8.setText(String.valueOf(""));
        jTextField9.setText(String.valueOf(""));
        jTextField10.setText(String.valueOf(""));
        jTextField11.setText(String.valueOf(""));
        jTextField12.setText(String.valueOf(""));
        jTextField13.setText(String.valueOf(""));
        jTextField14.setText(String.valueOf(""));
        jTextField15.setText(String.valueOf(""));
        jTextField16.setText(String.valueOf(""));
        jTextField17.setText(String.valueOf(""));
        jTextField18.setText(String.valueOf(""));
        jTextField19.setText(String.valueOf(""));
        jTextField20.setText(String.valueOf(""));
        jTextField21.setText(String.valueOf(""));
        jTextField22.setText(String.valueOf(""));
        jTextField23.setText(String.valueOf(""));
        jTextField24.setText(String.valueOf(""));
        jTextField25.setText(String.valueOf(""));
        
               
        
    }//GEN-LAST:event_limpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JTextField centro;
    private javax.swing.JLabel centroide;
    private javax.swing.JTextField errorD;
    private javax.swing.JTextField errora;
    private javax.swing.JTextField errorp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField10;
    public javax.swing.JTextField jTextField11;
    public javax.swing.JTextField jTextField12;
    public javax.swing.JTextField jTextField13;
    public javax.swing.JTextField jTextField14;
    public javax.swing.JTextField jTextField15;
    public javax.swing.JTextField jTextField16;
    public javax.swing.JTextField jTextField17;
    public javax.swing.JTextField jTextField18;
    public javax.swing.JTextField jTextField19;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField20;
    public javax.swing.JTextField jTextField21;
    public javax.swing.JTextField jTextField22;
    public javax.swing.JTextField jTextField23;
    public javax.swing.JTextField jTextField24;
    public javax.swing.JTextField jTextField25;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    public javax.swing.JTextField jTextField5;
    public javax.swing.JTextField jTextField6;
    public javax.swing.JTextField jTextField7;
    public javax.swing.JTextField jTextField8;
    public javax.swing.JTextField jTextField9;
    private javax.swing.JButton limpiar;
    public javax.swing.JTextField matriz;
    public javax.swing.JTextField matriz1;
    public javax.swing.JTextField matriz2;
    public javax.swing.JTextField matriz3;
    public javax.swing.JTextField matriz4;
    // End of variables declaration//GEN-END:variables
}
